USE PracABD1;

CREATE TABLESPACE TBLS_Clientes ADD DATAFILE 'DF_Clientes.ibd';
CREATE TABLESPACE TBLS_Juegos ADD DATAFILE 'DF_Juegos.ibd';
CREATE TABLESPACE TBLS_Clientes_Juegos ADD DATAFILE 'DF_ClientesJuegos.ibd';