USE PracABD1;

ALTER TABLE Clientes
ADD PRIMARY KEY (ClienteID);
 
ALTER TABLE Juegos
ADD PRIMARY KEY (JuegoID);

ALTER TABLE Clientes_Juegos
ADD PRIMARY KEY (ClienteID, JuegoID, FechaAlquiler);

ALTER TABLE Clientes_Juegos
ADD FOREIGN KEY (ClienteID) REFERENCES Clientes(ClienteID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE Clientes_Juegos
ADD FOREIGN KEY (JuegoID) REFERENCES Juegos(JuegoID) ON DELETE CASCADE ON UPDATE CASCADE;
